import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

tasks.withType<KotlinCompile> {
    kotlinOptions.allWarningsAsErrors = true
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
    maven("https://plugins.gradle.org/m2/")
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"
    id("com.github.johnrengelman.shadow") version "5.1.0"
    id("org.jlleitschuh.gradle.ktlint") version "8.2.0"

    // Apply the application plugin to add support for building a CLI application.
    application
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.0.1")
    implementation("com.expediagroup:graphql-kotlin-schema-generator:1.0.0-RC6")
    implementation("com.expediagroup:graphql-kotlin-federation:1.0.0-RC6")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.9")
    implementation("io.ktor:ktor-server-netty:1.2.4")
    implementation("io.ktor:ktor-jackson:1.2.4")
    implementation("org.slf4j:slf4j-simple:1.7.26")
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

ktlint {
    debug.set(true)
    enableExperimentalRules.set(true)
}

application {
    // Define the main class for the application
    mainClassName = "de.hello.kotlin.WebServiceKt"
}

tasks.withType<ShadowJar> {
}
